name: LuxeStays CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 24.1.0
  VITE_API_URL: "https://hd-luxestays-backend.onrender.com"

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/luxestays_front

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: frontend/luxestays_front/node_modules
        key: frontend-${{ hashFiles('frontend/luxestays_front/package-lock.json') }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build production
      run: npm run build

  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: server/node_modules
        key: backend-${{ hashFiles('server/package-lock.json') }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI_TEST }}

  deploy-production:
    needs: [frontend-ci, backend-ci]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy Backend to Render
      run: |
        curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI_PROD }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        NODE_ENV: production

    - name: Deploy Frontend to Render
      run: |
        curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
      env:
        VITE_API_URL: ${{ env.VITE_API_URL }}
